services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: recommender_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db
    # Adicionamos a flag --host 0.0.0.0 e a variável para desabilitar a checagem restritiva
    environment:
      - MLFLOW_HOST=0.0.0.0
      - MLFLOW_SERVER_ALLOWED_HOSTS=* 
    command: >
      mlflow server 
      --backend-store-uri sqlite:////mlflow.db 
      --default-artifact-root /mlruns 
      --host 0.0.0.0 
      --port 5000
      --allowed-hosts "*"

  recommender_app:
    build: .
    container_name: recommender_app
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://recommender_mlflow:5000
    # Adicione ou substitua o comando por este:
    tty: true
    stdin_open: true
    command: tail -f /dev/null