name: CD Pipeline

on:
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Training
        run: |
          # Usando a sintaxe nativa do docker (sem hífen)
          docker compose build recommender_app

      - name: Finalize Deployment
        if: success()
        run: echo "Treinamento concluído com sucesso!"
